def get_model_text(llm_response: LlmResponse) -> str:
    """Helper function to get the model text from the LLM response."""
    if (
        llm_response is None
        or llm_response.content is None
        or not llm_response.content.parts
    ):
        return ""

    return llm_response.content.parts[0].text or ""


def after_model_guardrail_callback(
    callback_context: CallbackContext,
    llm_response: LlmResponse
) -> GuardrailResult:
    """
    Tracks consecutive out-of-scope requests.

    - OOS response → increment out_of_scope_count
    - In-scope response → reset count to 0
    - Count >= 3 → trigger Human Escalation
    """

    model_output = get_model_text(llm_response).lower().strip()

    # Detect the standard OOS responses generated by the Root Agent.
    oos_indicators = [
        "outside of my scope",
        "outside of what i can directly assist",
        "outside of my expertise",
        "my focus is specifically on fashion",
        "my expertise is in fashion",
        "as a fashion assistant",
        "outside of the fashion",
        "related to wardrobe, styling, shopping, or booking",
        "fashion-related services",
    ]

    is_out_of_scope = any(
        phrase in model_output
        for phrase in oos_indicators
    )

    # Read current counter
    count = int(
        callback_context.variables.get("out_of_scope_count", 0)
    )

    if is_out_of_scope:
        # Consecutive OOS request
        count += 1
    else:
        # In-scope request resets the streak
        count = 0

    # Save updated counter
    callback_context.variables["out_of_scope_count"] = count

    # Escalate only after 3 consecutive OOS requests
    if is_out_of_scope and count >= 3:
        return create_guardrail_result(
            decision="TRIGGER",
            reason="Three consecutive out-of-scope requests detected."
        )

    return create_guardrail_result(
        decision="OK",
        reason=f"Out-of-scope count is {count}."
    )